name: Node CI

on: [push]

jobs:
  build-with-npm6:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["12", "14"]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: npm install, build, and test
        run: |
          npm ci
          npm install ink react
          npm run build
        env:
          CI: true

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["16"]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build
        env:
          CI: true
